name: lost_n_found
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  supercharged: ^2.1.1
  google_fonts: ^2.3.1
  get_cli: ^1.7.1
  get: 4.6.1
  flutter: 
    sdk: flutter
  get_storage: ^2.0.3
  form_field_validator: ^1.1.0
  carousel_slider: ^4.0.0
  image_picker: ^0.8.5
  convert: ^3.0.1
  http: ^0.13.4
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.15

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  

